In [1]:
import numpy as np   # It is an usual standard to use np for numpy

In [2]:
# Creating a vector and a matrix
v = np.array([1, 2, 3])
A = np.array([[1, 2], [3, 4], [5, 6]])

# Element-wise operations on vectors
v_add = v + 2
v_sub = v - 1
v_mul = v * 2
v_div = v / 2

print("Vector v:", v)
print("Matrix A:", A)
print("Element-wise addition (v + 2):", v_add)
print("Element-wise subtraction (v - 1):", v_sub)
print("Element-wise multiplication (v * 2):", v_mul)
print("Element-wise division (v / 2):", v_div)

Vector v: [1 2 3]
Matrix A: [[1 2]
 [3 4]
 [5 6]]
Element-wise addition (v + 2): [3 4 5]
Element-wise subtraction (v - 1): [0 1 2]
Element-wise multiplication (v * 2): [2 4 6]
Element-wise division (v / 2): [0.5 1.  1.5]


In [3]:
# Accessing and modifying elements
print("Original v:", v)
v[0] = 10  # Changing the first component of v to 10
print("Modified v:", v)

print("Original A:", A)
A[0, 1] = 9  # Changing the [0,1] (1st row, 2nd column) entry to 9
print("Modified A:", A)

Original v: [1 2 3]
Modified v: [10  2  3]
Original A: [[1 2]
 [3 4]
 [5 6]]
Modified A: [[1 9]
 [3 4]
 [5 6]]


In [4]:
# Creating a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Matrix A:\n", A)

# Printing the order (dimensions) of the matrix
print("Order (dimensions) of A: ",A.shape)
print("Number of rows in A: ",A.shape[0])
print("Number of columns in A: ",A.shape[1])

Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Order (dimensions) of A:  (4, 3)
Number of rows in A:  4
Number of columns in A:  3


NOTE THAT PYTHON INDEXING STARTS FROM 0

In [5]:
# Extracting an entry from the matrix
print(A[0,0]) # 1st row, 1st column entry

1


In [6]:
# Extracting a row from the matrix
print(A[1]) # 2nd row

[4 5 6]


In [7]:
# Extracting a column from the matrix
print(A[:,0]) # 1st column

[ 1  4  7 10]


In [8]:
# Python range function (default step-size is 1)
A1 = range(10) # default starting point is 0
print("A1: ",A1)
print("List of numbers in A1: ",list(A1))

A2 = range(-3, 7)
print("A2: ",A2)
print("List of numbers in A2: ",list(A2))

# Range with customized step-size
A3 = range(-3, 7, 2)  # step-size as 2
print("A3: ",A3)
print("List of numbers in A3: ",list(A3))

A1:  range(0, 10)
List of numbers in A1:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A2:  range(-3, 7)
List of numbers in A2:  [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]
A3:  range(-3, 7, 2)
List of numbers in A3:  [-3, -1, 1, 3, 5]


In [9]:
# Matrix multiplication

# Define matrices B and C
B = np.array([[1, 0], [0, 1], [1, 1]])
C = np.array([[1, 0, 1], [0, 1, 1]])

print("Matrix B:\n", B)
print("Matrix C:\n", C)


# Check if BC=CB
Prod1 = np.zeros((B.shape[0], C.shape[1]))  
for i in range(B.shape[0]):
    for j in range(C.shape[1]):
        for k in range(B.shape[1]):
            Prod1[i, j] = Prod1[i, j] + B[i, k] * C[k, j]
                
print("B * C \n", Prod1)

Prod2 = np.zeros((C.shape[0], B.shape[1]))
for i in range(C.shape[0]):
    for j in range(B.shape[1]):
        for k in range(C.shape[1]):
            Prod2[i, j] = Prod2[i, j] + C[i, k] * B[k, j]
                
print("C * B \n", Prod2)

Matrix B:
 [[1 0]
 [0 1]
 [1 1]]
Matrix C:
 [[1 0 1]
 [0 1 1]]
B * C 
 [[1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 2.]]
C * B 
 [[2. 1.]
 [1. 2.]]


In [10]:
# FUNCTION that performs matrix multiplication
def matrix_multiply(X, Y):
    result = np.zeros((X.shape[0], Y.shape[1]))
    for i in range(X.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(X.shape[1]):
                result[i, j] = result[i, j] + X[i, k] * Y[k, j]
    return result



# Define matrices B and C
B = np.array([[1, 0], [0, 1], [1, 1]])
C = np.array([[1, 0, 1], [0, 1, 1]])


print("Matrix B:\n", B)
print("Matrix C:\n", C)


# Calling the function to perform the required matrix multiplications
ProdBC = matrix_multiply(B, C)
print("B * C =\n", ProdBC)

ProdCB = matrix_multiply(C, B)
print("C * B =\n", ProdCB)

Matrix B:
 [[1 0]
 [0 1]
 [1 1]]
Matrix C:
 [[1 0 1]
 [0 1 1]]
B * C =
 [[1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 2.]]
C * B =
 [[2. 1.]
 [1. 2.]]


In [11]:
# Define matrix D
D = np.array([[1, 2], [2, 3]])
print("Matrix D:\n", D)

# Print transpose of D
print("Transpose of D:\n", D.T)


# Check if D is symmetric
print("Is D symmetric?", np.array_equal(D, D.T))


# Modify D to make it asymmetric
D[0, 1] = 5
print("Modified Matrix D:\n", D)
print("Transpose of Modified D:\n", D.T)
print("Is Modified D symmetric?", np.array_equal(D, D.T))

Matrix D:
 [[1 2]
 [2 3]]
Transpose of D:
 [[1 2]
 [2 3]]
Is D symmetric? True
Modified Matrix D:
 [[1 5]
 [2 3]]
Transpose of Modified D:
 [[1 2]
 [5 3]]
Is Modified D symmetric? False
