In [1]:
import numpy as np

In [2]:
# Create an identity matrix of size 2x2
I = np.eye(2)
print("Identity Matrix (2x2):\n", I)

# Define matrix C
C = np.array([[4, 7], [2, 6]])

# Compute the inverse of C
C_inv = np.linalg.inv(C)

# Verify by multiplying C with its inverse
identity_check = np.dot(C, C_inv)

print("Matrix C:\n", C)
print("Inverse of C:\n", C_inv)
print("C * C_inv:\n", identity_check)

Identity Matrix (2x2):
 [[1. 0.]
 [0. 1.]]
Matrix C:
 [[4 7]
 [2 6]]
Inverse of C:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
C * C_inv:
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [3]:
## The linear system Ax = b

# Define the coefficients matrix A and the constants vector b
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
print("Matrix A:\n", A)
print("Vector b:", b)

# Solve the system Ax = b
x = np.linalg.solve(A, b)
print("Solution x:", x)


# Verify by substituting the solution back into the equations
print("Verification:")
ProdAx = np.dot(A, x)
print("A*x = ", ProdAx)
print("Vector b:", b)
print("Is A*x = b? ", np.array_equal(ProdAx, b))

Matrix A:
 [[1 2]
 [3 4]]
Vector b: [ 5 11]
Solution x: [1. 2.]
Verification:
A*x =  [ 5. 11.]
Vector b: [ 5 11]
Is A*x = b?  True
