In [1]:
import numpy as np

In [2]:
# Matrix A
A = np.array([[1, 2, 3], [4, -5, 0], [-7, 8, -1], [-2, 3, 5]])
print("Matrix A:\n", A)

# Order of A
print("Order of A: ",A.shape)

Matrix A:
 [[ 1  2  3]
 [ 4 -5  0]
 [-7  8 -1]
 [-2  3  5]]
Order of A:  (4, 3)


In [3]:
# Computing the matrices A(A^T) and (A^T)A

C = np.dot(A, A.T)
D = np.dot(A.T, A)

print(C)
print(D)

[[ 14  -6   6  19]
 [ -6  41 -68 -23]
 [  6 -68 114  33]
 [ 19 -23  33  38]]
[[ 70 -80   0]
 [-80 102  13]
 [  0  13  35]]


In [4]:
# Checking whether A(A^T) and (A^T)A are symmetric

print("Order of A(A^T): ",C.shape)
print("Order of (A^T)A: ",D.shape)

AATSym = np.array_equal(C, C.T)
print("Is A(A^T) symmetric? ", AATSym)

ATASym = np.array_equal(D, D.T)
print("Is (A^T)A symmetric? ", AATSym)

Order of A(A^T):  (4, 4)
Order of (A^T)A:  (3, 3)
Is A(A^T) symmetric?  True
Is (A^T)A symmetric?  True


In [5]:
# Checking equality of an entry with its diagonally symmetric entry in A(A^T)

i = 1
j = 2

# As A(A^T) is a 4*4 matrix, enter i and j such that 0 <= i <= 3 and 0 <= j <= 3.

Entryij = np.dot(A[i], A.T[:,j])  # Dot product of ith row of A and jth column of A^T
Entryji = np.dot(A[j], A.T[:,i])  # Dot product of jth row of A and ith column of A^T

print("(ij)-th entry: ",Entryij)
print("(ji)-th entry: ",Entryji)

print("Equal? ",Entryij == Entryji)

(ij)-th entry:  -68
(ji)-th entry:  -68
Equal?  True


In [6]:
# Verifying that the matrix A(A^T) is symmetric using the dot products of rows and columns of A and A^T.

A = np.array([[1, 2, 3], [4, -5, 0], [-7, 8, -1], [-2, 3, 5]])
C = np.dot(A, A.T)

check = 1  # The matrix A(A^T) is symmetric if check remains as 1

for i in range(1, C.shape[0]):
    for j in range(C.shape[0]-1):
        if np.dot(A[i], A.T[:,j]) != np.dot(A[j], A.T[:,i]):
            check = 0
# Dot product of ith row of A and jth column of A^T should be the same as dot product of jth row of A and ith column of A^T
# for all pairs (i,j).

print("check = ",check)

check =  1


In [7]:
## EXERCISES
A = np.array([[1, -2], [5, 3], [-4, -1]])
B = np.array([[9, -2, 1, 0], [-1, 3, -2, 4]])
C = np.array([[-3, 1], [-5, 2], [1, 0], [-2, 1]])


# EXERCISE 1: VERIFY THE ASSOCIATIVITY OF MATRIX MULTIPLICATION, THAT IS, (AB)C = A(BC).
# EXERCISE 2: VERIFY THAT (ABC)^T = C^T B^T A^T.

In [ ]:
# SOLUTION FOR EXERCISE 1






In [ ]:
# SOLUTION FOR EXERCISE 2




